Bug of the PART from the channel
Please see messages (---<---) and replies (--->---)

1.   ChatSharp has joined to the #MyChannel
2.   Darev has joined to the #MyChannel
3.   Darev has part from the #MyChannel
4.  Try to part of ChatSharp from the #MyChannel channel

---<--- NICK ChatSharp
---<--- USER ChatSharp hostname servername :ChatSharp
...
---<--- JOIN #MyChannel
1.   ChatSharp has joined to the #MyChannel

--->--- 221 ChatSharp :+ixpemJMn
---<--- WHOIS ChatSharp
--->---:ChatSharp!ChatSharp@=fPbaz.66.70.188.95.dsl.krasnet.ru JOIN
:#MyChannel
--->--- 331 ChatSharp #MyChannel :No topic is set.
--->--- 353 ChatSharp = #MyChannel :@ChatSharp
--->--- 366 ChatSharp #MyChannel :End of /NAMES list.
---<--- MODE #MyChannel
--->--- 311 ChatSharp ChatSharp ChatSharp
=fPbaz.66.70.188.95.dsl.krasnet.ru * :ChatSharp
--->--- 319 ChatSharp ChatSharp :@#MyChannel
--->--- 312 ChatSharp ChatSharp java.webchat.org :ConferenceRoom
4.0.7-SEC by WebMaster Incorporated
--->--- 334 ChatSharp ChatSharp location :Krasnoyarsk, Krasnoyarsk,
Russian Federation
--->--- 318 ChatSharp ChatSharp :End of /WHOIS list.
--->--- 324 ChatSharp #MyChannel +
--->--- 329 ChatSharp #MyChannel 1486941359
--->---:Darev!Darev@=fPbaz.66.70.188.95.dsl.krasnet.ru JOIN :#MyChannel
2.   Darev has joined to the #MyChannel

--->---:Darev!Darev@=fPbaz.66.70.188.95.dsl.krasnet.ru PART #MyChannel
3.   Darev has part from the #MyChannel
Remove "#MyChannel" channel from IrcClient.Channels.
See ChatSharp.Handlers.ChannelHandlers.HandlePart(...) for details

4.  Now I try to part of ChatSharp from the #MyChannel channel, but I
see:

System.InvalidOperationException: Client is not present in channel.

because  "#MyChannel" is not exists in the IrcClient.Channels.

See IrcClient.PartChannel(string channel) for details.

I think, Good idea to remove channel from IrcClient.Channels only if
channell is not exists in the IrcClient.Users.Channels